name: api_ekko

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  logger: ^1.0.0
  get_server: ^1.0.0
  uuid: ^3.0.3

  # get_server:
  #   path: "C:/Projetos/Personal/libs/get_server"
  # get_server:
  #   git:
  #     url: https://github.com/Katekko/get_server.git
  #     ref: master

dev_dependencies:
  build_runner: ^1.12.2
  json_serializable: ^4.1.0